### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by danielester** [gvanem/Dump1090#1]
After building the project with Visual Studio 2017, after a while,  I get a runtime error because km_kts variabile is not initialized, so:

const char *km_kts=NULL;
After this, everything seems ok.
Thank you!

**Comment by gvanem** [comment]
Congrats for filing the first issue here and on Github in general.

But that must be some old version; there is no `const char *km_kts;` there now.

Was it a Runtime Error related to the use of `-RTCu` in Debug-mode?

**Comment by gvanem** [comment]
Seems to be fixed. Closing.
