### ISSUE TITLE
Operation with BlogV4 RTL-SDR dongle

### ISSUE THREAD

**Issue by Padanian** [gvanem/Dump1090#15]
Does this fork correcly initialise the tuner of the BlogV4 version of the RTL-SDR dongle?
It looks like other windows version of dump1090 are unable to initialise it.

**Comment by gvanem** [comment]
Why is that an issue? Dump1090 tunes tunes 1090 MHz and a *BlogV4* dongle should be handled differently only
when tuned below 28.8 MHz AFAIK. 

So do you have a *BlogV4* dongle and have troubles using it with this Dump1090 program?

But yes, `librtlsdr.c` and `tuner_r82xx.c` should handle  a *BlogV4* dongle. E.g. see:
https://github.com/gvanem/Dump1090/blob/0f3a5c2fddf2305daa9ed94ae005c8aee9924e08/src/externals/rtl-sdr/tuner_r82xx.c#L1181-L1185

**Comment by Padanian** [comment]
Yes, I have issues with other forks of dump1090, not yet with this one. I wanted to make sure before actually adopting it. 
Thanks for your answer. I'll give it a try.

**Comment by Padanian** [comment]
Works perfectly. Best fork of dump1090 ever.

**Comment by gvanem** [comment]
Not an issue. Closing.
