### ISSUE TITLE
Unable to download aircrafts database, link seems to be dead

### ISSUE THREAD

**Issue by nikolan123** [gvanem/Dump1090#20]
On first launch it tries to download https://opensky-network.org/datasets/metadata/aircraftDatabase.zip, but that link seems dead and is now a 404. The link https://opensky-network.org/datasets/metadata/ linked on the readme is also a 404
![image](https://github.com/user-attachments/assets/0df43269-5349-4c9d-ab71-3419f0af3685)
![image](https://github.com/user-attachments/assets/3913e473-4010-4775-907e-959eb687695a)

**Comment by gvanem** [comment]
I also just noted the same issue. Change the link in `dump1090.cfg` to:
```diff
@@ -45,7 +45,7 @@ aircrafts = %~dp0\aircraft-database.csv
 # This can be done even when another 'dump1090.exe' is running with the same
 # `$(aircrafts).sqlite' file.
 #
-aircrafts-url = https://opensky-network.org/datasets/metadata/aircraftDatabase.zip
+aircrafts-url = https://s3.opensky-network.org/data-samples/metadata/aircraftDatabase.zip

```

**Comment by nikolan123** [comment]
That fixed it, thanks

**Comment by gvanem** [comment]
> The updated URL seems to timeout.

I see the same, even no response on `ping s3.opensky-network.org`.
But that URL worked 2 days ago. Probably a temporary issue. Ref: https://downforeveryoneorjustme.com/opensky-network.org

> I switched the URL to https://registry.faa.gov/database/ReleasableAircraft.zip 

That .ZIP has a totally incompatible layout and content. Not usable.

**Comment by mufaka** [comment]
I assumed it was OK because I can actually run the app and the output above stated it created 381,559 records.  With the original URL, the app fails to launch.
