### ISSUE TITLE
API failure, binary data decompression failed

### ISSUE THREAD

**Issue by iicey** [gvanem/Dump1090#3]
old api：https://globe.adsbexchange.com/data/globe_{id}.binCraft
new api：https://globe.adsbexchange.com/re-api/?binCraft&zstd&box=-90,90,-180,180

**Comment by gvanem** [comment]
You need to add some *meat* to this PR to make it clearer.
First, where/how does this occur exactly. More details please.

**Comment by gvanem** [comment]
@iicey It seems you're a Troll. Create a better PR next time. Closing
