### ISSUE TITLE
Cross-Origin Resource Sharing (CORS) Error

### ISSUE THREAD

**Issue by amitpathania** [gvanem/Dump1090#4]
I am trying to read json file running on dump1090 webserver from my web application. However, I am getting CORS request error and I am not able to read the data/json file.

`
Access to XMLHttpRequest at 'http://localhost:8080/data.json' from origin 'http://localhost:8000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
`

I checked up on internet the reason and ways to remove the error. There is requirement to add CORS header in responding server. Access-Control-Allow-Origin: *
Can you add this header when you are creating webserver response in your code? or if you can help me to add this header. 
`static const char *set_headers (const connection *cli,
                                const char       *content_type)`

Thanks

**Comment by amitpathania** [comment]
Getting error while compiling using make command.
make -f Makefile.Windows CC=cl
Makefile.Windows:141: *** Unsupported 'CPU='.  Stop.

**Comment by gvanem** [comment]
> Makefile.Windows:141: *** Unsupported 'CPU='. Stop.

Add an env-var `set CPU=x64` (or `x86`) depending on the `cl.exe` compiler you want to use.

>  The build tools for visual studio 2019 (v142) cannot be found

Edit the `.vcxproj` file; replace `v142` with what you've got.

**Comment by gvanem** [comment]
>  The item "externals\rtl-sdr\trace.h" already exists under the filter "".

Oh I see it's duplicated. Remove the extra.

**Comment by amitpathania** [comment]
dump1090 server response to python requests:
 HTTP server (port 8080):
           3 HTTP GET requests received.
           0 HTTP 400 replies sent.
           0 HTTP 404 replies sent.
           0 HTTP/WebSocket upgrades.
           0 server connection "keep-alive".
           2 client connection "keep-alive".
           3 client connections accepted.
           3 client connections removed.
           0 client connections unknown.

**Comment by gvanem** [comment]
So your web-application is in Python? So what has this to do with dump1090? Be specific.
So I'm not so keen on adding this CORS-header.

**Comment by gvanem** [comment]
I've added this CORS header in 
https://github.com/gvanem/Dump1090/commit/406011b615519eba04d6eec08453b2d271fab42c

Hence closing; your issue seems nothing to do with dump1090. But your Python script.
